version: '3.6'

services:
  llm_bot_backend:
    build:
      context: ./llm-bot-backend
    image: llm_bot_backend
    container_name: llm_bot_backend_container
    volumes:
      - media:/media
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  llm_bot_frontend:
    build:
      context: ./llm-bot-frontend
    image: llm_bot_frontend
    container_name: llm_bot_frontend_container
    volumes:
      - vue_build:/vue/dist
  postgres:
    build: ./postgres
    image: postgres
    container_name: postgres_container
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_container
    volumes:
      - vue_build:/var/www/llm_bot
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/nginx-setup.conf
    ports:
      - "80:80"
volumes:
  vue_build:
  media:
  db:
